# Generated by Django 2.1.4 on 2019-01-27 05:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcontent',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
