# Generated by Django 2.1.4 on 2019-01-25 04:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decorator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decorator', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jar_number', models.IntegerField(default=0)),
                ('jar_name', models.CharField(default='', max_length=50)),
                ('comment', models.CharField(blank=True, max_length=50)),
                ('jar_image', models.FileField(upload_to='JarAlbum')),
                ('production_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('decorator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='album.Decorator')),
                ('product_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.Product')),
                ('sold_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.CheckOut')),
            ],
        ),
        migrations.CreateModel(
            name='JarGoalKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='JarIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=200)),
            ],
        ),
    ]
